# Generated by Django 4.0.3 on 2022-07-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('usuarios', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
