# Generated by Django 4.0.3 on 2022-07-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carreras', models.IntegerField()),
                ('nombre_carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.IntegerField()),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('vive_en', models.CharField(max_length=100)),
                ('vive_con', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=20)),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=12)),
                ('centro_estudio', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facultad', models.IntegerField()),
                ('nombre_facultad', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.IntegerField()),
                ('nombre_amigo', models.CharField(max_length=100)),
                ('carrera_amigo', models.CharField(max_length=75)),
                ('medio_referencia', models.CharField(max_length=15)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recibos', models.IntegerField()),
                ('vivienda', models.CharField(max_length=20)),
                ('luz', models.CharField(max_length=20)),
                ('agua', models.CharField(max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_propiedades', models.IntegerField()),
                ('nombre_propiedad', models.CharField(max_length=300)),
                ('precio_propiedad', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_familiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo_familiar', models.IntegerField()),
                ('cantidad_familiares', models.IntegerField()),
                ('ingresos_familiares', models.FloatField()),
                ('egresos_familiares', models.FloatField()),
                ('detalles_egresos_familiares', models.CharField(max_length=500)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.IntegerField()),
                ('direccion_exacta', models.CharField(max_length=100)),
                ('telefono_fijo', models.CharField(max_length=9)),
                ('celular', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.facultad'),
        ),
    ]
