# Generated by Django 4.0.3 on 2022-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0002_carrera_estudiantes_facultad_remove_usuario_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='edad_estudiante',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='otro_vive_con',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='otro_vive_en',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='primer_apellido',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='segundo_apellido',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referencia',
            name='otros_medios',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombre_estudiante',
            field=models.CharField(max_length=50),
        ),
    ]
