# Generated by Django 4.0.3 on 2022-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0003_estudiantes_edad_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='beca_escuela',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
