# Generated by Django 4.0.3 on 2022-07-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0004_estudiantes_beca_escuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='id_carreras',
        ),
        migrations.RemoveField(
            model_name='contacto_estudiante',
            name='id_contacto',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='id_estudiante',
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='id_facultad',
        ),
        migrations.RemoveField(
            model_name='grupo_familiare',
            name='id_grupo_familiar',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='id_propiedades',
        ),
        migrations.RemoveField(
            model_name='recibos',
            name='id_recibos',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='id_referencia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
    ]
