# Generated by Django 4.0.3 on 2022-07-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0007_datos_neurona_datos_economicos_familia_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='tipo_ingreso',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
