# Generated by Django 4.0.3 on 2022-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0008_estudiantes_tipo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienes_familiare',
            name='total_cancelado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='bachiller_opcion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='bachiller_opcion2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='beca_precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='ciclo_estudiado',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='ciclo_estudiado2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='cuota_pagaba',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='cuota_pagaba2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='lugar_procedencia',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='lugar_procedencia2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='pago_cuota',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='pago_cuota2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
