# Generated by Django 4.0.3 on 2022-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0010_alter_bienes_familiare_cantidad_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='beca_precio',
            field=models.CharField(max_length=3),
        ),
    ]
