# Generated by Django 4.0.3 on 2022-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0012_alter_bienes_familiare_cantidad_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_familiare',
            name='egresos_familiares',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='grupo_familiare',
            name='ingresos_familiares',
            field=models.CharField(max_length=150),
        ),
    ]
