# Generated by Django 4.0.3 on 2022-07-19 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EstudioSocioeconomico', '0014_bienes_familiare_usuario_contacto_estudiante_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
