# Generated by Django 4.0.3 on 2022-07-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0018_alter_estudiantes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_neurona',
            name='cuota_estudiante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos_neurona',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes'),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='beca_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='bienes_muebles_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='cuota_institucion_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='egresos_familiares_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='egresos_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='estado_civil_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='ingresos_familiares_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='miembros_fam_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='propiedades_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='vehiculo_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='vive_con_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_neurona',
            name='vive_en_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_d', models.CharField(max_length=100)),
                ('responsable_d', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EstudioSocioeconomico.estudiantes')),
            ],
        ),
    ]
