# Generated by Django 4.0.3 on 2022-07-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EstudioSocioeconomico', '0019_datos_neurona_cuota_estudiante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_neurona',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='datos_neurona',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
