# Generated by Django 4.0.3 on 2022-08-06 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EstudioSocioeconomico', '0020_remove_datos_neurona_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion',
            old_name='estudiante_d',
            new_name='nombre_aspirante',
        ),
        migrations.RenameField(
            model_name='declaracion',
            old_name='responsable_d',
            new_name='nombre_responsable',
        ),
        migrations.AddField(
            model_name='declaracion',
            name='firma_aspirante',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracion',
            name='firma_responsable',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
