# Generated by Django 4.0.3 on 2022-08-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudioSocioeconomico', '0021_rename_estudiante_d_declaracion_nombre_aspirante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='fecha_firmo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='firma_responsable',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='nombre_responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
