from collections import UserList
from operator import mod
from pyexpat import model
from unicodedata import unidata_version
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser



# Create your models here.
class Usuario(AbstractBaseUser):
    username = models.CharField('Nombre de usuario', unique=True, max_length=100)
    email = models.EmailField('Correo Electronico', max_length=254, unique=True)
    nombres = models.CharField('Nombres', max_length=200, null= True, blank= True)
    apellidos = models.CharField('apellidos', max_length=150, blank=True, null=True)
    estado = models.CharField('estado', max_length=2, blank=True, null=True )
    usuario_activo = models.BooleanField(default= True)
    usuario_administrador = models.BooleanField(default= False)

    USENAME_FIELD = 'username'
    REQUIRED_FIELDS: list['email', 'nombres', 'apellidos']

    def __str__(self):
        return f'usuario {self.username}'

    def has_perm(self,perm,obj= None):
        return True

    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.usuario_administrador

class Facultad(models.Model):
    nombre_facultad=models.CharField(max_length=50)

class Carrera(models.Model):
    nombre_carrera=models.CharField(max_length=100)
    facultad=models.ForeignKey(Facultad, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

class Estudiantes(models.Model):
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='usuario')
    primer_apellido=models.CharField(max_length=20)
    segundo_apellido=models.CharField(max_length=20)
    nombre_estudiante=models.CharField(max_length=50)
    carrera=models.ForeignKey(Carrera, null=True, blank=True, on_delete=models.CASCADE)
    vive_en=models.CharField(max_length=100)
    otro_vive_en=models.CharField(max_length=25)
    vive_con=models.CharField(max_length=50)
    otro_vive_con=models.CharField(max_length=50)
    estado_civil=models.CharField(max_length=20)
    lugar_nacimiento=models.CharField(max_length=50)
    fecha_nacimiento=models.CharField(max_length=12)
    edad_estudiante=models.CharField(max_length=3)
    centro_estudio=models.CharField(max_length=50)
    beca_escuela=models.CharField(max_length=3)
    beca_precio=models.CharField(max_length=3)
    tipo_titulo=models.CharField(max_length=20)
    tipo_ingreso=models.CharField(max_length=20)
    lugar_procedencia=models.CharField(max_length=50)
    lugar_procedencia2=models.CharField(max_length=50)
    bachiller_opcion=models.CharField(max_length=20)
    bachiller_opcion2=models.CharField(max_length=20)
    ciclo_estudiado=models.CharField(max_length=30)
    ciclo_estudiado2=models.CharField(max_length=30)
    cuota_pagaba=models.CharField(max_length=15)
    cuota_pagaba2=models.CharField(max_length=15)
    pago_cuota=models.CharField(max_length=30)
    pago_cuota2=models.CharField(max_length=30)
    estado=models.IntegerField()

class Contacto_Estudiante(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    direccion_exacta=models.CharField(max_length=100)
    telefono_fijo=models.CharField(max_length=9)
    celular=models.CharField(max_length=9)
    email=models.CharField(max_length=50)

class Propiedades(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    nombre_propiedad=models.CharField(max_length=300)
    precio_propiedad=models.CharField(max_length=15)

class Grupo_familiare(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    cantidad_familiares=models.CharField(max_length=15)
    ingresos_familiares=models.CharField(max_length=150)
    egresos_familiares=models.CharField(max_length=150)
    nombre=models.CharField(max_length=75)
    nombre2=models.CharField(max_length=75)
    nombre3=models.CharField(max_length=75)
    nombre4=models.CharField(max_length=75)
    nombre5=models.CharField(max_length=75)
    nombre6=models.CharField(max_length=75)
    nombre7=models.CharField(max_length=75)
    nombre8=models.CharField(max_length=75)
    nombre9=models.CharField(max_length=75)
    nombre10=models.CharField(max_length=75)
    parentesco=models.CharField(max_length=25)
    parentesco2=models.CharField(max_length=25)
    parentesco3=models.CharField(max_length=25)
    parentesco4=models.CharField(max_length=25)
    parentesco5=models.CharField(max_length=25)
    parentesco6=models.CharField(max_length=25)
    parentesco7=models.CharField(max_length=25)
    parentesco8=models.CharField(max_length=25)
    parentesco9=models.CharField(max_length=25)
    parentesco10=models.CharField(max_length=25)
    edad_familiar=models.CharField(max_length=3)
    edad_familiar2=models.CharField(max_length=3)
    edad_familiar3=models.CharField(max_length=3)
    edad_familiar4=models.CharField(max_length=3)
    edad_familiar5=models.CharField(max_length=3)
    edad_familiar6=models.CharField(max_length=3)
    edad_familiar7=models.CharField(max_length=3)
    edad_familiar8=models.CharField(max_length=3)
    edad_familiar9=models.CharField(max_length=3)
    edad_familiar10=models.CharField(max_length=3)
    profesion=models.CharField(max_length=75)
    profesion2=models.CharField(max_length=75)
    profesion3=models.CharField(max_length=75)
    profesion4=models.CharField(max_length=75)
    profesion5=models.CharField(max_length=75)
    profesion6=models.CharField(max_length=75)
    profesion7=models.CharField(max_length=75)
    profesion8=models.CharField(max_length=75)
    profesion9=models.CharField(max_length=75)
    profesion10=models.CharField(max_length=75)
    lugar_trabajo=models.CharField(max_length=60)
    lugar_trabajo2=models.CharField(max_length=60)
    lugar_trabajo3=models.CharField(max_length=60)
    lugar_trabajo4=models.CharField(max_length=60)
    lugar_trabajo5=models.CharField(max_length=60)
    lugar_trabajo6=models.CharField(max_length=60)
    lugar_trabajo7=models.CharField(max_length=60)
    lugar_trabajo8=models.CharField(max_length=60)
    lugar_trabajo9=models.CharField(max_length=60)
    lugar_trabajo10=models.CharField(max_length=60)

class Educacion_Familia(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    nombre_familiar=models.CharField(max_length=75)
    nombre_familiar2=models.CharField(max_length=75)
    nombre_familiar3=models.CharField(max_length=75)
    grado_educacion=models.CharField(max_length=75)
    grado_educacion2=models.CharField(max_length=75)
    grado_educacion3=models.CharField(max_length=75)
    centro_estudios=models.CharField(max_length=75)
    centro_estudios2=models.CharField(max_length=75)
    centro_estudios3=models.CharField(max_length=75)
    cuota=models.CharField(max_length=15)
    cuota2=models.CharField(max_length=15)
    cuota3=models.CharField(max_length=15)
    responsable_cuota=models.CharField(max_length=50)
    responsable_cuota2=models.CharField(max_length=50)
    responsable_cuota3=models.CharField(max_length=50)

class Bienes_Familiare(models.Model):
    propiedad_familia=models.CharField(max_length=30)
    propiedad_familia2=models.CharField(max_length=30)
    propiedad_familia3=models.CharField(max_length=30)
    direccion_propiedad=models.CharField(max_length=150)
    direccion_propiedad2=models.CharField(max_length=150)
    direccion_propiedad3=models.CharField(max_length=150)
    n_habitaciones=models.CharField(max_length=3)
    n_habitaciones2=models.CharField(max_length=3)
    n_habitaciones3=models.CharField(max_length=3)
    n_baños=models.CharField(max_length=3)
    n_baños2=models.CharField(max_length=3)
    n_baños3=models.CharField(max_length=3)
    inst_vendedora=models.CharField(max_length=100)
    inst_vendedora2=models.CharField(max_length=100)
    inst_vendedora3=models.CharField(max_length=100)
    cuota_mensual=models.CharField(max_length=15)
    cuota_mensual2=models.CharField(max_length=15)
    cuota_mensual3=models.CharField(max_length=15)
    valor_actual=models.CharField(max_length=15)
    valor_actual2=models.CharField(max_length=15)
    valor_actual3=models.CharField(max_length=15)
    total_cancelado=models.CharField(max_length=15)
    posee_vehiculo=models.CharField(max_length=3)
    tipo_vehiculo=models.CharField(max_length=50)
    tipo_vehiculo2=models.CharField(max_length=50)
    marca_vehiculo=models.CharField(max_length=50)
    marca_vehiculo2=models.CharField(max_length=50)
    año_vehiculo=models.CharField(max_length=50)
    año_vehiculo2=models.CharField(max_length=50)
    valor_vehiculo=models.CharField(max_length=15)
    valor_vehiculo2=models.CharField(max_length=15)
    cantidad_mueble_sala=models.CharField(max_length=15)
    valor_mueble_sala=models.CharField(max_length=15)
    cantidad_mueble_comedor=models.CharField(max_length=15)
    valor_mueble_comedor=models.CharField(max_length=15)
    cantidad_refri=models.CharField(max_length=15)
    valor_refri=models.CharField(max_length=15)
    cantidad_cocina=models.CharField(max_length=15)
    valor_cocina=models.CharField(max_length=15)
    cantidad_horno=models.CharField(max_length=15)
    valor_horno=models.CharField(max_length=15)
    cantidad_licuadora=models.CharField(max_length=15)
    valor_licuadora=models.CharField(max_length=15)
    cantidad_tv=models.CharField(max_length=15)
    valor_tv=models.CharField(max_length=15)
    cantidad_teatro=models.CharField(max_length=15)
    valor_teatro=models.CharField(max_length=15)
    cantidad_sonido=models.CharField(max_length=15)
    valor_sonido=models.CharField(max_length=15)
    cantidad_camara=models.CharField(max_length=15)
    valor_camara=models.CharField(max_length=15)
    cantidad_compu=models.CharField(max_length=15)
    valor_compu=models.CharField(max_length=15)
    cantidad_lavadora=models.CharField(max_length=15)
    valor_lavadora=models.CharField(max_length=15)
    cantidad_secadora=models.CharField(max_length=15)
    valor_secadora=models.CharField(max_length=15)
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

class datos_economicos_familia(models.Model):
    trabajo_alumno=models.CharField(max_length=75)
    salario_alumno=models.CharField(max_length=15)
    descuento_alumno=models.CharField(max_length=15)
    aporte_liquido=models.CharField(max_length=15)
    trabajo_mama=models.CharField(max_length=75)
    salario_mama=models.CharField(max_length=15)
    descuento_mama=models.CharField(max_length=15)
    aporte_mama=models.CharField(max_length=15)
    trabajo_papa=models.CharField(max_length=75)
    salario_papa=models.CharField(max_length=15)
    descuento_papa=models.CharField(max_length=15)
    aporte_papa=models.CharField(max_length=15)
    trabajo_remesas=models.CharField(max_length=75)
    salario_remesas=models.CharField(max_length=15)
    descuento_remesas=models.CharField(max_length=15)
    aporte_remesas=models.CharField(max_length=15)
    trabajo_otros=models.CharField(max_length=75)
    salario_otros=models.CharField(max_length=15)
    descuento_otros=models.CharField(max_length=15)
    aporte_otros=models.CharField(max_length=15)
    cantidad_alimento=models.CharField(max_length=15)
    detalles_alimento=models.CharField(max_length=150)
    cantidad_pago_casa=models.CharField(max_length=15)
    detalles_pago_casa=models.CharField(max_length=150)
    cantidad_abono_prestamo=models.CharField(max_length=15)
    detalles_abono_prestamo=models.CharField(max_length=150)
    cantidad_abono_tarjetas=models.CharField(max_length=15)
    detalles_abono_tarjetas=models.CharField(max_length=150)
    cantidad_serbasicos=models.CharField(max_length=15)
    detalles_serbasicos=models.CharField(max_length=150)
    cantidad_educacion=models.CharField(max_length=15)
    detalles_educacion=models.CharField(max_length=150)
    cantidad_transporte=models.CharField(max_length=15)
    detalles_transporte=models.CharField(max_length=150)
    cantidad_combustible=models.CharField(max_length=15)
    detalles_combustible=models.CharField(max_length=150)
    cantidad_ayuda_parientes=models.CharField(max_length=15)
    detalles_ayuda_parientes=models.CharField(max_length=150)
    cantidad_salud=models.CharField(max_length=15)
    detalles_salud=models.CharField(max_length=150)
    cantidad_internet=models.CharField(max_length=15)
    detalles_internet=models.CharField(max_length=150)
    cantidad_cable=models.CharField(max_length=15)
    detalles_cable=models.CharField(max_length=150)
    cantidad_otros=models.CharField(max_length=15)
    detalles_otros=models.CharField(max_length=150)
    observaciones=models.CharField(max_length=140)
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

class Referencia(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    nombre_amigo=models.CharField(max_length=100)
    carrera_amigo=models.CharField(max_length=75)
    medio_referencia=models.CharField(max_length=15)
    otros_medios=models.CharField(max_length=30)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

class Recibos(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    vivienda=models.CharField(max_length=20)
    luz=models.CharField(max_length=20)
    agua=models.CharField(max_length=20)

class Declaracion(models.Model):
    estudiante=models.ForeignKey(Estudiantes, null=True, blank=True, on_delete=models.CASCADE)
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    nombre_aspirante = models.CharField(max_length=100)
    firma_aspirante = models.CharField(max_length=3)
    nombre_responsable = models.CharField(max_length=100, null=True, blank=True)
    firma_responsable = models.CharField(max_length=3, null=True, blank=True)
    fecha_firmo = models.CharField(max_length=10, null=True, blank=True )


class datos_neurona(models.Model):
    usuario=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    vive_en_n=models.IntegerField(null=True, blank=True)
    vive_con_n=models.IntegerField(null=True, blank=True)
    estado_civil_n=models.IntegerField(null=True, blank=True)
    cuota_institucion_n=models.IntegerField(null=True, blank=True)
    beca_n=models.IntegerField(null=True, blank=True)
    miembros_fam_n=models.IntegerField(null=True, blank=True)
    egresos_n=models.IntegerField(null=True, blank=True)
    propiedades_n=models.IntegerField(null=True, blank=True)
    vehiculo_n=models.IntegerField(null=True, blank=True)
    bienes_muebles_n=models.IntegerField(null=True, blank=True)
    ingresos_familiares_n=models.IntegerField(null=True, blank=True)
    egresos_familiares_n=models.IntegerField(null=True, blank=True)
    puntuacion=models.IntegerField(null=True, blank=True)
    cuota_estudiante=models.IntegerField(null=True, blank=True)






